import type { NextPage } from "next";
import Head from "next/head";
import { FaGithub } from "react-icons/fa";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create Nex App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center w-1/2 min-h-screen mx-auto">
        <h1 className="text-2xl flex items-center gap-3">
          Teste GitHub Actions
          <FaGithub size={36} />
        </h1>
      </div>
    </>
  );
};

export default Home;
